"""add_subscription_fields

Revision ID: 7c0b28fbe359
Revises: 
Create Date: 2026-06-14 23:26:52.477322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c0b28fbe359'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('subscription_tier', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('accessed_books', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('accessed_audiobooks', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'accessed_audiobooks')
    op.drop_column('users', 'accessed_books')
    op.drop_column('users', 'subscription_tier')
    # ### end Alembic commands ###
